Work I Have Done
================

A lot of the work I currently do revolves around the code that powers sites as opposed the designs that the user sees. I do offer design services however, and will try to include any examples of this. Also, due to the nature of my work I the vast majority of my experience is working with existing sites as opposed to creating new ones -- not that I cannot do that, I just generally work with agencies as opposed to directly working with clients, however I am moving towards this area as I develop skills that would allow me to support customers as well as they deserve.

Following are examples of sites I have worked on professionally, and also a few examples of personal projects or work I have done for free.

Professional Work
-----------------

ABRSM
~~~~~

When the new ABRSM site launched, the slideshow at the top of the page originally used Flash, and I was contracted to replace this quickly with a version that used HTML5 and JavaScript. I was able to replicate the behaviour of the original Flash slideshow and create a version that worked more smoothly and cleanly than the original using custom JQuery.


Music Medals
~~~~~~~~~~~~

When ABRSM wanted a site to launch their Music Medals scheme, a site was needed that allowed users to browse and search a large database of publications to find out which were suitable for their instrument, group size, or skill level.

I created a small CMS and back-end data entry tool to enable employees to input data quickly and efficiently, and a lightning fast bespoke search which fulfilled all the goals of the project.

Several years later, I was able to provide the support needed so that the agency could give the site a complete re-design and transition smoothly to the new branding without any issues.


CBSO
~~~~

CBSO was one of the original clients of an agency I work with, and as such the site has undergone a huge amount of improvements and upgrades in the last ten or so years. I had to learn to work with and extend a custom framework that was used for the original site, which I did and thus can update and add features fairly quickly.